import './globals.css'
import {Montserrat} from 'next/font/google'

const montserrat = Montserrat({
  weight: ['100', '200', '500'],
  styles: ['italic', 'bold', 'normal'],
  subsets: ['latin']
})

export const metadata = {
  title: 'App next crud',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} bg-zinc-900 container mx-auto flex justify-center items-center h-screen`}>{children}</body>
    </html>
  )
}
